development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: essaii.notifications@gmail.com
  :password: den1altheory
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: essaii.notifications@gmail.com
  :password: den1altheory
  :enable_starttls_auto: true